export const TRANSLATION_LIST_REQUEST = 'TRANSLATION_LIST_REQUEST';
export const TRANSLATION_LIST_SUCCESS = 'TRANSLATION_LIST_SUCCESS';
export const TRANSLATION_LIST_FAIL = 'TRANSLATION_LIST_FAIL';

export const TRANSLATION_DETAILS_REQUEST = 'TRANSLATION_DETAILS_REQUEST';
export const TRANSLATION_DETAILS_SUCCESS = 'TRANSLATION_DETAILS_SUCCESS';
export const TRANSLATION_DETAILS_FAIL = 'TRANSLATION_DETAILS_FAIL';

export const TRANSLATION_CREATE_REQUEST = 'TRANSLATION_CREATE_REQUEST';
export const TRANSLATION_CREATE_SUCCESS = 'TRANSLATION_CREATE_SUCCESS';
export const TRANSLATION_CREATE_FAIL = 'TRANSLATION_CREATE_FAIL';
export const TRANSLATION_CREATE_RESET = 'TRANSLATION_CREATE_RESET';

export const TRANSLATION_UPDATE_REQUEST = 'TRANSLATION_UPDATE_REQUEST';
export const TRANSLATION_UPDATE_SUCCESS = 'TRANSLATION_UPDATE_SUCCESS';
export const TRANSLATION_UPDATE_FAIL = 'TRANSLATION_UPDATE_FAIL';
export const TRANSLATION_UPDATE_RESET = 'TRANSLATION_UPDATE_RESET';

export const TRANSLATION_DELETE_REQUEST = 'TRANSLATION_DELETE_REQUEST';
export const TRANSLATION_DELETE_SUCCESS = 'TRANSLATION_DELETE_SUCCESS';
export const TRANSLATION_DELETE_FAIL = 'TRANSLATION_DELETE_FAIL';
export const TRANSLATION_DELETE_RESET = 'TRANSLATION_DELETE_RESET';
